config/routes.rb
Rails.application.routes.draw do
  get '/articles/search', to: 'articles#search'
  devise_for :users
  resources :users
 resources :articles do
 resources :comments
 end
 root "articles#index" #mowimy ze strona i metoda index jest strona glowna
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :articles
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

   protected

   def configure_devise_permitted_parameters
     registration_params = [:username, :email, :password, :password_confirmation]

     if params[:action] == 'update'
       devise_parameter_sanitizer.for(:account_update) {
         |u| u.permit(registration_params << :current_password)
       }
     elsif params[:action] == 'create'
       devise_parameter_sanitizer.for(:sign_up) {
         |u| u.permit(registration_params)
       }
     end
   end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @arti=Article.all
  end

  def show
    @arti=Article.find(params[:id]) #params[:id] szuka id obiektu i przekazuje do metody find
    @comm=Comment.all
  end

  def new #metoda tylko dla formularzu
    @arti=Article.new #tworzy nowy pusty obiekt
  end

  def create #metoda do zatwierdzenia danych dlatego dziala tylko na przycisniecie przycisku zatwierdzenia nie ma wlasnego szablonu
    arti=Article.new(article_params)
    arti.user_id=current_user.id
    arti.save
    redirect_to arti
  end

  def destroy
    arti=Article.find(params[:id])
    arti.destroy
    redirect_to root_path

  end

  def search
    @arti=Article.all
    @arti.each{|f|
      if f.title==params[:name]
        @arti1=f
      end
      }
  end

  def edit
    @arti=Article.find(params[:id])
  end

  def update
    arti=Article.find(params[:id])
    arti.update_attributes(article_params)
    redirect_to arti
  end

  :private
  def article_params #umozliwia dostep do atrybutow stosowany do obrony danych przed innymi uzytkownikami
    params.require(:article).permit(:title,:body)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @arti=Article.find(params[:article_id])
    @comm = Comment.new
  end

  def create
    comm = Comment.new(comment_params)
    comm.article_id=params[:article_id]
    comm.save
    @arti=Article.find(params[:article_id])
    redirect_to article_path(comm.article)
  end

    :private
  def comment_params #umozliwia dostep do atrybutow stosowany do obrony danych przed innymi uzytkownikami
    params.require(:comment).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user=User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/edit.html.erb
<%= form_for @arti do |f| %>
<p><%= f.label :title %></p>
<p><%= f.text_field :title %></p>
<p><%= f.label :body %></p>
<p><%= f.text_area :body, :rows => 20, :cols => 30 %></p>
<%= f.submit %>
<%end%>

app/views/articles/index.html.erb
<% if current_user.nil? %>
  <nav>
    <%= link_to("Sign in",new_user_session_path) %>
    <%= link_to("Sign up", new_user_registration_path) %>
  </nav>
<%else%>
  <div class="white_space">
    <% @arti.each do |article| %>
    <p>  <%= link_to(article.title,article) %><br/><%=article.body%>
      <p>Liczba komentarzy: <%= article.comments.count %></p>
      <% if article.user_id==current_user.id %>
    <%= link_to("Usun",article_path(article),data: {confirm: "Na pewno?"},method: :delete) %></p>
    <%end%>
    <%end%>
  </div>
<p><%= link_to("Nowy",new_article_path) %></p>
<%end%>

app/views/articles/new.html.erb
<%= form_for @arti do |f|%> <!-- tworzy formularz (podawanie danych ) jako argument podajemy jakis pusty obiekt-->
<p>
 <%= f.label :title %>
  <%= f.text_field :title %>
<p>
  <%= f.label :body%>
  <%= f.text_field :body %>
</p>

<%= f.submit %> <!-- submite przekierowuje na metode create -->

  <% end%>

app/views/articles/search.html.erb
<p>
  <%= @arti1.title %>
  <%= @arti1.body %>
</p>

app/views/articles/show.html.erb
<div class="white_space">
<h1><%= @arti.title %></h1>
<b>Autor: <%= @arti.user.email %><% if @arti.user_id==current_user.id%> <%= link_to("Edytuj", edit_article_path(@arti)) %><%end%></b>
<%= link_to(@arti.user.email,user_path(@arti.user)) %>
<p "white_space"><%= @arti.body %></p>


<h3> Komentarze: </h3>

<% @arti.comments.each do |com| %>
  <p>Data: <%= com.created_at %></p>
  <p><%= com.body %></p>
<%end%>

<p><%=link_to("Dodaj nowy komentarz", new_article_comment_path(@arti))%></p>
</div>
<p><%= link_to("Wróć",articles_path) %>

app/views/comments/new.html.erb
<%=form_for [@arti,@comm] do |f| %>
<p> Podaj treść: </p>
<p> <%= f.text_field :body %> </p>
<%=f.submit%>
 <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h3 id="naglowek">BLOGisLOVE BLOGisLIFE</h3>

  <div class="user_head">
    <% if current_user!=nil %>
    Witaj, <%=link_to(current_user.username,user_path(current_user), class: "head_button")%>
    <%= link_to("Sign out", destroy_user_session_path,method: :delete, class: "head_button") %>
    <%end%>
  </div>

  <div>
    <%= form_tag('/articles/search', method: :get) do%>
    <div class="search_text_field_tag"> <%= text_field_tag :name %></div>
    <div class="search_button"> <%= submit_tag "Search"%></div>
  <%end%>
  </div>
<%= yield %>

</body>
</html>

app/views/users/show.html.erb
<%= @user.email %>